# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_name', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('inflation', models.FloatField(default=0.0)),
                ('result', models.IntegerField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
