# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-02 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='users',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='facebook_name',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
