# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inflation',
            field=models.FloatField(),
        ),
    ]
